---
deployment:
  tasks:
    - export DEPLOYPATH=/home/garba/public_html/
    - /bin/rm -Rf favicon.ico
    - /bin/rm -Rf index.html
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
    - /bin/cp -R dist/spa/* $DEPLOYPATH
