---
deployment:
  tasks:
    - export DEPLOYPATH=/home/garba/public_html/
    - /bin/rm -Rf favicon.ico
    - /bin/rm -Rf index.html
    - /bin/rm -Rf css
    - /bin/cp -R dist/spa/* $DEPLOYPATH
    
