version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"

  ib-app:
    image: vew-build:latest
    ports:
      - "8888:80"
    depends_on:
      - nginx
    volumes:
      - ./home/dimpy/Documents/Docker/Infinitybrains-fronted:/var/lib/docker/volumes/vue-developer2  # This line creates a volume mapping
    environment:
      - NODE_ENV=production  # Adjust environment variables as needed
